name: Store XSD File

on: [push, pull_request]

jobs:
  store-xsd:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload XSD File
        uses: actions/upload-artifact@v4
        with:
          name: xsd-schema
          path: src/main/java/org/example/reference/router-conf.xsd
